my:
   greeting: hello1
app:
   name: spring-config
   discription: This is discription of ${app.name}
   list.value: ramesh,suresh,ganesh,mukesh
   db:
     value: "{url:'localhost:3000/....',username:'test',password:'test'}"
db:
   connectionUrl: "localhost:8731/test"
   port: 3210
   username: RUSHABH1
   password: LOLOL1
management.endpoints.web.exposure.include: "*"
